### ISSUE TITLE
integers changed to decimal in various fields

### ISSUE THREAD

**Issue by tsherlockcraig** [psrc/combine_gtfs_feeds#15]
[note: this issue is likely not worth fixing as the issue does not prevent import into transit-service-analyst but I'm logging the issue with the relevant documentation briefly just in case I encounter it again and want to submit a corresponding PR later on.]

`combine_gtfs_feeds run -g C:\Users\craigth\pythonwork\gtfs\subgroup -s 20220815 -o C:\Users\craigth\pythonwork\gtfs_stops`

Two input files
-[ICT.zip](https://github.com/psrc/combine_gtfs_feeds/files/9404274/ICT.zip)
-[RCT.zip](https://github.com/psrc/combine_gtfs_feeds/files/9404277/RCT.zip)
 
Output file: 
[gtfs_stops.zip](https://github.com/psrc/combine_gtfs_feeds/files/9404290/gtfs_stops.zip)

In `routes.txt` and other files, integers in columns like `route_sort_order` have been transformed into decimals by `.0` being appended. File fails validation per [MobilityData validator](https://github.com/MobilityData/gtfs-validator) "invalid_integer".

**Comment by stefancoe** [comment]
Pandas is treating these columns as floats. I will add a data validator so that the columns adhere to the data type specified in the GTFS schema.

**Comment by stefancoe** [comment]
Closed by this commit:
https://github.com/psrc/combine_gtfs_feeds/commit/39c49b75c1cbebb936ac2d07058095f4d4d35498

**Comment by tsherlockcraig** [comment]
Hi Stefan--

Earlier when reviewing new version I didn't double check this issue, only the shapes issue. Still very minor, but I wanted to note that decimals are still being added in some files. See output files below containing stops.txt and trips.txt, where the former has decimals added to 'location_type' and 'wheelchair_boarding', and the latter has decimals added to 'direction_id' and 'block_id'.

[decimal files.zip](https://github.com/psrc/combine_gtfs_feeds/files/10580402/decimal.files.zip)

**Comment by stefancoe** [comment]
@tsherlockcraig can you try running it with a [new release](https://pypi.org/project/combine-gtfs-feeds/#description) I just published. You can update the package with pip using the folloiwng:

pip install combine-gtfs-feeds --upgrade
