### ISSUE TITLE
combine() missing 1 required positional argument: 'logger'

### ISSUE THREAD

**Issue by isaacwist** [psrc/combine_gtfs_feeds#17]
Hi,

I'm trying to follow the example shown for cli.run.combine with three Chicago GTFS feeds using an input directory, date, and output directory as the arguments, but I keep running into this error: 

"combine() missing 1 required positional argument: 'logger'"

I've tried setting the logger argument to null etc. and I can't figure out what data type it takes. Any help would be much appreciated!

Isaac

**Comment by stefancoe** [comment]
@isaacwist I have replicated this error and am working on a fix. I'll post back later once its all taken care of. Thanks!

**Comment by stefancoe** [comment]
@isaacwist I just added a new release (0.1.4) to PyPI that should address the issue you were having. Can you test it? You can update your python env by running this:

pip install combine-gtfs-feeds --upgrade

**Comment by isaacwist** [comment]
Wow, thanks so much for the quick reply! I'll give it a shot in the next
few days.

best,
Isaac Wisthuff

**Comment by isaacwist** [comment]
Now I'm getting the error below:

Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?77680cfd-03a4-463e-bb90-b55656665842)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File c:\Users\isaac\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\indexes\base.py:3802, in Index.get_loc(self, key, method, tolerance)
   3801 try:
-> 3802     return self._engine.get_loc(casted_key)
   3803 except KeyError as err:

File c:\Users\isaac\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\_libs\index.pyx:138, in pandas._libs.index.IndexEngine.get_loc()

File c:\Users\isaac\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\_libs\index.pyx:165, in pandas._libs.index.IndexEngine.get_loc()

File pandas\_libs\hashtable_class_helper.pxi:5745, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas\_libs\hashtable_class_helper.pxi:5753, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'agency_id'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[3], line 1
----> 1 merged_gtfs = cli.run.combine(gtfs_dir, service_date, output_path)
      2 merged_gtfs.routes_df.head()
      3 merged_gtfs.export_feed()
...
   3807     #  InvalidIndexError. Otherwise we fall through and re-raise
   3808     #  the TypeError.
   3809     self._check_indexing_error(key)

KeyError: 'agency_id'

**Comment by stefancoe** [comment]
@isaacwist is there any chance you can share the GTFS feeds you are trying to combine and I can run it on my end? It probably wont work as an attachment so maybe google drive or something? Thanks!

**Comment by stefancoe** [comment]
Also, check to make sure that the agency.txt file in each feed has an agency_id field.

**Comment by isaacwist** [comment]
Ended up needing to add an agency_id field for the CTA agency.txt which
cleared up that error, but now I'm having an issue with "start_date". From
what I can tell, 20190304 overlaps with the calendar.txt contents for each
agency, and all of them have this field... Here's a link
<https://drive.google.com/drive/folders/1CUqoWH6BiFF8xNLZHG9IZcD9gvq03ZZN?usp=sharing>to
the files. Thanks again for your help, I don't typically do too much
programming like this.

Isaac

**Comment by stefancoe** [comment]
@isaacwist Thanks for sharing the GTFS feeds! There are some issues with the feeds:

- metra_2019 is has no records for calendar_dates, which is usually used to add or remove service_ids specified in calendar.txt
- metra_2019 calendar.txt has leading spaces in front of column names, so in python/pandas the column ' start_date' should be 'start_date'.
- pace_2019 does not have a shapes.txt file. While this is not required by GTFS, it is typically included and was a requirement for this tool as it would be odd to have a combined feed that only had shape records for some of the trips.  
 
I have created issues for all of these because I think they are things the tool should address since GTFS is such a loose standard. I have implemented the fixes and created the output GTFS from your input feeds. I just need to clean up the code and publish a new version to pypi. I'll let you know when it is ready to test. Thanks!

-Stefan

**Comment by isaacwist** [comment]
Great. Thank you so much Stefan! One follow up question if you don't mind:
My plan was to analyze the merged feed using R's tidytransit because it
provides very high level tools for calculating travel time matrices.
Ideally I'd like to find a Python alternative because that's the language
that I'm most familiar with. Do you have any recommendations? NetworkX etc.?

Isaac

**Comment by stefancoe** [comment]
@isaacwist I just published a [new release](https://pypi.org/project/combine-gtfs-feeds/) to pypi. Hopefully this will work with no issues!

Here are a couple of links that might help with building travel time matrices. 
https://github.com/kuanb/peartree
https://2021sp-final-project-filipwodnicki.readthedocs.io/en/latest/
http://kuanbutts.com/2018/12/24/peartree-with-walk-network/

I used the third link as the starting point for a project a few years back and thought it worked well. Feel to reach out if you need any help.

-Stefan

**Comment by isaacwist** [comment]
Thanks so so much for your help! The script works perfectly.

Isaac
