### ISSUE TITLE
KeyError start_date 

### ISSUE THREAD

**Issue by ckarnes** [psrc/combine_gtfs_feeds#24]
I am running into an issue where every single call I make to merge GTFS it results in a KeyError start_date.  There's no logging to tell me which file this is affecting.  I have tried this with combinations of four different agencies in Canada as well as Pierce Transit and Intercity Transit.  Any thoughts about what I might be doing wrong?

The calendar.txt file is present in each of the subfolders.

Directory structure is as follows:
/GTFS/19/
agency.txt          fare_attributes.txt  routes.txt  stops.txt       transfers.txt
calendar_dates.txt  feed_info.txt        shapes.txt  stop_times.txt  trips.txt
/GTFS/3/
agency.txt          calendar.txt         feed_info.txt  shapes.txt  stop_times.txt
calendar_dates.txt  fare_attributes.txt  routes.txt     stops.txt   trips.txt
/output/ <empty>

combine_gtfs_feeds run -g "GTFS" -s "20230505" -o "output"

Traceback (most recent call last):
  File "/opt/conda/bin/combine_gtfs_feeds", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/combine_gtfs_feeds/cli/main.py", line 19, in main
    sys.exit(combine.execute())
  File "/opt/conda/lib/python3.8/site-packages/combine_gtfs_feeds/cli/cli.py", line 28, in execute
    args.func(args)
  File "/opt/conda/lib/python3.8/site-packages/combine_gtfs_feeds/cli/run.py", line 509, in run
    feeds = combine(args.gtfs_dir, args.service_date, args.output_dir, logger)
  File "/opt/conda/lib/python3.8/site-packages/combine_gtfs_feeds/cli/run.py", line 578, in combine
    service_id_list = get_service_ids(
  File "/opt/conda/lib/python3.8/site-packages/combine_gtfs_feeds/cli/run.py", line 125, in get_service_ids
    (calendar["start_date"] <= service_date)
  File "/home/datascience/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/datascience/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'start_date'

**Comment by stefancoe** [comment]
Is calendar.txt in the /GTFS/19 dir? I see calendar_dates.txt listed but not calendar.txt. I recently made some changes to the code to allow only calendar_dates.txt, but I did not update pypi yet. I should be able to do that pretty quickly. If you have calendar.txt in both feeds and the column start_date is present in both, feel free to send/share the feeds with me and I'll take a closer look.

**Comment by ckarnes** [comment]
You are right, it looks like Intercity is operating entirely off of calendar_dates.txt in the OTD from ST.

However the two files I was working with from Canada were:

Montreal
https://storage.googleapis.com/storage/v1/b/mdb-latest/o/ca-quebec-societe-de-transport-de-laval-gtfs-749.zip?alt=media
Laval
https://storage.googleapis.com/storage/v1/b/mdb-latest/o/ca-quebec-societe-de-transport-de-montreal-gtfs-1221.zip?alt=media

Got these from the Mobility Database CSV catalog.
https://database.mobilitydata.org/

**Comment by stefancoe** [comment]
Ok- I updated the version on pypi, which should work with feeds missing calendar.txt. Can you try upgrading to version 0.1.7?

pip install combine-gtfs-feeds==0.1.7

https://pypi.org/manage/project/combine-gtfs-feeds/releases/

Let me know if this work. Thanks!

**Comment by stefancoe** [comment]
@ckarnes In order to get the code to work the two feeds linked above I had to fix this issue:
https://github.com/psrc/combine_gtfs_feeds/issues/25

I have updated pypi with release 0.1.8 to reflect this change.
